### ISSUE TITLE
transfer to posthtml ?

### ISSUE THREAD

**Issue by Scrum** [island205/posthtml-web-component#9]
@island205 Hi, I am a `posthtml` maintainer and I am interested in developing all packages related to this project. I would like to suggest that you transport your package to a `posthtml` organization for operational support and development of your package.

Let me know what you think about it.

**Comment by island205** [comment]
OK, I transfer it now.

---

Please add me to `posthtml` organization for this transfer.

**Comment by Scrum** [comment]
@island205 Good day wherever you are now.

To transfer you to the organization, you need your activity in the organization. We need time to understand that you benefit the organization itself.

You can also give me the rights of the creator of your package so that I can transfer it to the organization while retaining all your rights to this package

**Comment by island205** [comment]
@Scrum You have the rights now

**Comment by Scrum** [comment]
@island205 Unfortunately, the `collaborator` does not have enough rights to have the `settings` option in which the `transfer` button is available. To move I must be with rights `owners`

**Comment by island205** [comment]
@Scrum requested

**Comment by Scrum** [comment]
@island205 transfer is done. Please check access to your repository.

**Comment by island205** [comment]
@Scrum Accessible
